name: composer-ai
namespacePrefix: composer-ai-
# Git Repository for the ArgoCD Application
repo:
  url: https://github.com/lpanza/appOfApps.git # Change This on Fork
  branch: main
# Namespace for the ArgoCD Application
gitops:
  namespaceSuffix: -runtime-int
# Passing this value to all of the sub-applications to make it so we can dynamically figure out urls
clusterDomain: apps.stc-ai-e1-dev.bpis.p1.openshiftapps.com
# Default Values File for the Helm Chart
defaultValuesFile: values.yaml
# Applications to be deployed
applications:
  - name: vllm-model
    path: vllm
    namespaceSuffix: -runtime-int
  - name: weaviate
    path: weaviate
    namespaceSuffix: -runtime-int
    enabled: false
  - name: elasticsearch
    path: elasticsearch
    namespaceSuffix: -runtime-int
  - name: kfp-pipeline
    path: kfp
    namespaceSuffix: -runtime-int
  - name: quarkus-llm-router
    path: conductor/quarkus-llm-router
    namespaceSuffix: -runtime-int
  - name: chatbot-ui
    path: chatbot-ui
    namespaceSuffix: -runtime-int
    # Add ignoreDifferences to allow deployment to be updated by ImageStream
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/spec/containers/0/image
  - name: mongodb
    path: conductor/mongodb
    namespaceSuffix: -runtime-int
  - name: bootstrap
    path: util/bootstrap
    namespaceSuffix: -runtime-int
